// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	stdlog "github.com/robowealth-mutual-fund/stdlog"
	mock "github.com/stretchr/testify/mock"

	zerolog "github.com/rs/zerolog"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields:
func (_m *Logger) Debug() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *Logger) Error() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// Fatal provides a mock function with given fields:
func (_m *Logger) Fatal() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// Info provides a mock function with given fields:
func (_m *Logger) Info() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// Log provides a mock function with given fields:
func (_m *Logger) Log() *zerolog.Logger {
	ret := _m.Called()

	var r0 *zerolog.Logger
	if rf, ok := ret.Get(0).(func() *zerolog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Logger)
		}
	}

	return r0
}

// Panic provides a mock function with given fields:
func (_m *Logger) Panic() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// Warn provides a mock function with given fields:
func (_m *Logger) Warn() stdlog.Event {
	ret := _m.Called()

	var r0 stdlog.Event
	if rf, ok := ret.Get(0).(func() stdlog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Event)
		}
	}

	return r0
}

// With provides a mock function with given fields:
func (_m *Logger) With() stdlog.Context {
	ret := _m.Called()

	var r0 stdlog.Context
	if rf, ok := ret.Get(0).(func() stdlog.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stdlog.Context)
		}
	}

	return r0
}

type mockConstructorTestingTNewLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t mockConstructorTestingTNewLogger) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
